clusterName: "opensearch-cluster"
replicaCount: 2
image:
  tag: "2.4.1"
persistence:
  enabled: true
  size: 30Gi
resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1"
    memory: "4Gi"
